version: '3.1'
services:
  mongo1:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tmaxrobo
      MONGO_INITDB_ROOT_PASSWORD: tmaxrobo
      MONGO_INITDB_DATABASE: ra
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - ra-net
    command:
      - mongod --replSet replication
  mongo2:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tmaxrobo
      MONGO_INITDB_ROOT_PASSWORD: tmaxrobo
      MONGO_INITDB_DATABASE: ra
    ports:
      - 27018:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - ra-net
    command:
      - mongod --replSet replication
    depends_on:
      - mongo1
  mongo3:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: tmaxrobo
      MONGO_INITDB_ROOT_PASSWORD: tmaxrobo
      MONGO_INITDB_DATABASE: ra
    ports:
      - 27019:27017
    volumes:
      - ./mongo-data:/data/db
    networks:
      - ra-net
    command:
      - mongod --replSet replication
    depends_on:
      - mongo2
networks:
  ra-net:
    name: ra-net
    driver: bridge
