#version: '3.1'
#services:
#  mongo1:
#    image: mongo:4.4.3
##    container_name: mongodb
#    command: mongod --replSet rs0 --port 27017
##    restart: always
##    environment:
##      MONGO_INITDB_ROOT_USERNAME: tmaxrobo
##      MONGO_INITDB_ROOT_PASSWORD: tmaxrobo
##      MONGO_INITDB_DATABASE: ra
#    ports:
#      - 27017:27017
#    volumes:
#      - ./mongoRepl/mongo1:/data/db
#    networks:
#      - ra-net
#  mongo2:
#    image: mongo:4.4.3
#    command: mongod --replSet rs0 --port 27018
#    ports:
#      - 27018:27018
#    volumes:
#      - ./mongoRepl/mongo2:/data/db
#    networks:
#      - ra-net
#  mongo3:
#    image: mongo:4.4.3
#    command: mongod --replSet rs0 --port 27019
#    ports:
#      - 27019:27019
#    volumes:
#      - ./mongoRepl/mongo3:/data/db
#    networks:
#      - ra-net
#
#networks:
#  ra-net:
#    name: ra-net
#    driver: bridge
#
#version: '3.1'
#services:
#  mongo:
#    image: mongo
#    container_name: mongodb
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: tmaxrobo
#      MONGO_INITDB_ROOT_PASSWORD: tmaxrobo
#      MONGO_INITDB_DATABASE: ra
#    ports:
#      - 27017:27017
#    volumes:
#      - ./mongo-data:/data/db
#    networks:
#      - ra-net
#networks:
#  ra-net:
#    name: ra-net
#    driver: bridge