spring:
  messages:
    basename: errors
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: ra
      username: tmaxrobo
      password: tmaxrobo
      authentication-database: admin
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 195757371436-t9lqvlimk2n6t5fdmamoup2ft0p9cfv9.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  simulation:
    strategies:
      - ppo
      - ew
      - gmv
      - mdp
      - mvo
      - rp
      - iv
      - bl
      - kospi
      - s&p500
  ai:
    url: http://192.168.154.50:9001
    host: triton-mms.kserve-test.example.com
    callBackUrl: http://192.168.155.91:8080