spring:
  messages:
    basename: errors
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.154.143:3306/RA?serverTimezone=UTC&characterEncoding=UTF-8
#    username: root
#    password: 0000
  data:
    mongodb:
      uri: mongodb://192.168.158.143:9042,192.168.158.143:9142,192.168.158.143:9242/ra?replicaset=docker-rs&connectTimeoutMS=3000&readPreference=secondaryPreferred
  redis:
    host: 192.168.158.143
    port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 420615974321-2m32k4ln8avlbgtgvd9js3a918g0amo6.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://192.168.158.141:80
  simulation:
    strategies:
      - ppo-growth
      - ppo-neutral
      - ppo-stable
      - ew
      - gmv
      - mdp
      - mvo
      - rp
      - iv
      - kospi
      - snp
  ai:
    url: http://192.168.153.44:9001
    path: /v2/models/triton-mms/infer
    host: triton-mms.kserve-test.example.com
    callBackUrl: http://192.168.158.141:8080/api/v1/simulation/callback
  trading:
    engineAddress: http://192.168.154.105:35000
    path: /simulate
    callBackUrl: http://192.168.158.141:8080/api/v1/portfolios/{0}/callback
logging:
  level:
    kr:
      co:
        tmax:
          rabackend: debug
slack:
  token: xoxb-1630331899815-3174643984272-If83e91hT5dGSRUZlPHqjAVy
  channel:
    monitor: C035511GZNU
    error: C035FGZ3BE3
    test: C034TH2N6HX
    etc: C03555Y23DE
