spring:
  messages:
    basename: errors
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ra
      username: tmaxrobo
      password: tmaxrobo
      authentication-database: admin
      Connectiontimeoutms: 10000 # TCP connection timeout, MS
      Readtimeoutms: 15000 # TCP read timeout, MS
      Poolmaxwaittimes: 3000 # the waiting time of client blocking when no connection is available in the connection pool, in milliseconds
      Connection maxidletimems: 60000
      Connectionmaxlifetimems: 120000
      Heartbeat frequency MS: 20000 # heartbeat detection sending frequency, unit: ms
      Minheartbeat frequency MS: 8000 # minimum heartbeat detection sending frequency, in milliseconds
      Heartbeat connection timeouts MS: 10000 # heartbeat detection TCP connection timeout, unit: ms
      Heartbeat readtimeouts: 15000
      Connectionsperhost: 100 # TCP connections per host
      Minconnectionsperhost: 5 # minimum number of TCP connections per host
      #The multiplier is used to calculate how many threads are allowed to block while waiting for available TCP connections. The algorithm is threadallowedtoblock for connection multiplier * connections perhost. The current configuration allows 10 * 20 threads to block
      threadsAllowedToBlockForConnectionMultiplier: 10
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 195757371436-t9lqvlimk2n6t5fdmamoup2ft0p9cfv9.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://robo.tmax.co.kr:8888
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
  simulation:
    strategies:
      - ppo-growth
      - ppo-neutral
      - ppo-stable
      - ew
      - gmv
      - mdp
      - mvo
      - rp
      - iv
      - kospi
      - snp
  ai:
    url: http://192.168.153.44:9001
    path: /v2/models/triton-mms/infer
    host: triton-mms.kserve-test.example.com
    callBackUrl: http://192.168.153.102:8080/api/v1/simulation/callback
logging:
  level:
    kr:
      co:
        tmax:
          rabackend: debug
